export const Products =  [
    {
      id: 1,
      name: 'Nike Air Zoom Pegasus 38',
      category: 'Running Shoes',
      price: 1200000,
      image: 'https://image.goat.com/crop/2200/attachments/product_template_pictures/images/062/904/107/original/DJ0823_001.png.png',
      description: 'The Nike Air Zoom Pegasus 38 provides responsive cushioning for your runs, featuring a breathable mesh upper and Zoom Air units in the forefoot and heel.',
    },
    {
      id: 2,
      name: 'Jordan Delta 2',
      category: 'Running Shoes',
      price: 1500000,
      image: 'https://www.thenextsole.com/storage/images/CV8121-011.png',
      description: 'The Jordan Delta 2 offers a mix of comfort and style with plush foam and visible Nike React cushioning. Its lightweight design and durability make it an excellent choice for running.',
    },
    {
      id: 3,
      name: 'Nike React Infinity Run Flyknit',
      category: 'Running Shoes',
      price: 1300000,
      image: 'https://cdn.shopify.com/s/files/1/1654/7905/products/DJ5396-100-PHSRH001-2000_0206e47b-c52a-4a91-9ea6-fbf5b4fe363d.png?v=1625778662',
      description: 'Designed to keep you running, the Nike React Infinity Run Flyknit provides stability and cushioning. The Flyknit upper ensures a secure and comfortable fit.',
    },
    {
      id: 4,
      name: 'Air Jordan 1 Retro High OG',
      category: 'Casual Shoes',
      price: 1800000,
      image: 'https://cdn.shopify.com/s/files/1/0050/3326/3173/products/Nike-Air-Jordan-1-Black-Toe-Satin-WMNS-CD0461-016-Sneakers-Heat-2.png?v=1571146090',
      description: "The Air Jordan 1 Retro High OG is an iconic sneaker known for its style and cultural impact. With premium materials and timeless design, it's perfect for casual wear.",
    },
    {
      id: 5,
      name: 'Nike Air Max 270',
      category: 'Casual Shoes',
      price: 1600000,
      image: 'https://cms-cdn.thesolesupplier.co.uk/2019/01/Nike-Air-Max-270-Blue-Black-AH8050-019_w900.png',
      description: "The Nike Air Max 270 delivers both style and comfort with its large Max Air unit and sleek design. It's an ideal choice for casual, everyday use.",
    },
    {
      id: 6,
      name: 'Jordan Why Not Zer0.4',
      category: 'Running Shoes',
      price: 1700000,
      image: 'https://image.goat.com/750/attachments/product_template_pictures/images/050/582/789/original/722495_00.png.png',
      description: "Russell Westbrook's signature shoe, the Jordan Why Not Zer0.4, is built for explosive on-court performance. It combines bold design elements with top-notch technology.",
    },
    {
      id: 7,
      name: 'Nike React Element 55',
      category: 'Casual Shoes',
      price: 1400000,
      image: 'https://i.pinimg.com/originals/9b/66/52/9b66520ca430e5e3d7f3b8bcd6143865.png',
      description: "The Nike React Element 55 offers a futuristic design and React foam cushioning for all-day comfort. It's a versatile choice for casual outings.",
    },
    {
      id: 8,
      name: 'Jordan 6 Rings',
      category: 'Casual Shoes',
      price: 1900000,
      image: 'https://2app.kicksonfire.com/kofapp/upload/events_images/ipad_jordan-6-rings-white-red-0.png',
      description: "Inspired by MJ's championship legacy, the Jordan 6 Rings combines elements from six iconic Jordan shoes. Its stylish design makes it a standout choice for casual occasions.",
    },
  ];